
const TRW_HEADINGS = {
"corporate-law": "Corporate Services",
"commercial-law": "Commercial Services",
"international-business": "International Business",
"regulatory-compliance": "Regulatory Compliance",
"banking-finance": "Banking & Finance",
"investment-law": "Investment Law",
"equity": "Capital Markets",
"fintech-crypto": "FinTech & Crypto",
"business-immigration": "Immigration & Visa Services",
"family-immigration": "Immigration & Visa Services",
"investor-visas": "Immigration & Visa Services",
"citizenship-naturalization": "Immigration & Visa Services",
"real-estate": "Real Estate Services",
"property-development": "Property Development",
"construction-law": "Construction Law",
"land-acquisition": "Land Acquisition",
"family-divorce": "Family Law Services",
"family-custody": "Family Law Services",
"family-matrimonial": "Family Law Services",
"family-international": "International Family Law",
"adr-arbitration": "Arbitration",
"adr-mediation": "Mediation",
"adr-conciliation": "Conciliation",
"adr-other": "Other ADR Mechanisms",
"criminal-domestic": "Domestic Criminal Law",
"criminal-international": "International Criminal Law",
"criminal-corporate": "Corporate Criminal Defense",
"criminal-compliance": "Criminal Compliance",
"ip-domestic": "Domestic IP Law",
"ip-international": "International IP Law",
"ip-enforcement": "IP Enforcement",
"ip-licensing": "IP Licensing & Tech Transfer",
"corporate-tax": "Corporate Tax",
"indirect-tax": "Indirect Tax (VAT & Customs)",
"international-tax": "International Tax & Transfer Pricing",
"tax-controversy": "Tax Controversy & Litigation",
"hc-writs": "Writs & Constitutional",
"hc-civil": "Civil Appellate & Revisional",
"hc-criminal": "Criminal Appellate & Revisional",
"hc-special": "Company, Admiralty & Special Benches",};
const P=(slug,label)=>({t:label,u:`https://tahmidurrahman.com/placeholder/${slug}`});
const U={
companyFormation:"https://tahmidurrahman.com/private-limited-company-in-bangladesh/",
companyRegistration:"https://tahmidurrahman.com/company-registration-lawyer-bangladesh/",
mergersAcq:"https://tahmidurrahman.com/mergers-and-acquisitions-in-bangladesh-a-complete-guide/",
corporateGovernance:"https://tahmidurrahman.com/corporate-lawyers-in-bangladesh/",
businessLicensing:"https://tahmidurrahman.com/licenses-for-doing-business-in-bangladesh/",
foreignInvestment:"https://tahmidurrahman.com/category/foreign-investment/"
};
const TRW_SERVICES={
"corporate-law":[
{t:"Company Formation",u:U.companyFormation},
{t:"Company Registration",u:U.companyRegistration},
{t:"Mergers & Acquisitions",u:U.mergersAcq},
{t:"Corporate Governance",u:U.corporateGovernance},
{t:"Business Licensing",u:U.businessLicensing},
{t:"Foreign Investment",u:U.foreignInvestment},
{t:"Joint Ventures",u:"https://tahmidurrahman.com/joint-ventures-in-bangladesh/"},
{"t":"Corporate Restructuring","u":"https://tahmidurrahman.com/corporate-restructuring/"},
{"t":"Due Diligence","u":"https://tahmidurrahman.com/due-diligence/"},
{t:"Corporate Compliance",u:"https://tahmidurrahman.com/corporate-compliance/"},
{"t":"Shareholder Agreements","u":"https://tahmidurrahman.com/shareholder-agreements/"},
{t:"Board Advisory",u:"https://tahmidurrahman.com/board-advisory/"},
{t:"Corporate Secretarial",u:"https://tahmidurrahman.com/corporate-secretarial-services/"},
{t:"Exit Strategies",u:"https://tahmidurrahman.com/form-i-94-explained-how-the-arrival-departure-record-tracks-u-s-entry-and-exit-and-why-it-matters/"},
{t:"Corporate Tax Planning",u:"https://tahmidurrahman.com/corporate-tax-planning-in-bangladesh/"},
{t:"Business Valuation",u:"https://tahmidurrahman.com/business-valuation/"}
],
"commercial-law": [{t:"Contract Law",u:"https://tahmidurrahman.com/contract-law/"},{t:"Commercial Agreements",u:"https://tahmidurrahman.com/commercial-agreements/"},{t:"Breach of Contract",u:"https://tahmidurrahman.com/breach-of-contract/"},{t:"Trade & Export",u:"https://tahmidurrahman.com/trade-export/"},{t:"Commercial Litigation",u:"https://tahmidurrahman.com/commercial-litigation/"},{t:"Factory Setup",u:"https://tahmidurrahman.com/factory-setup/"},{t:"Distribution Agreements",u:"https://tahmidurrahman.com/distribution-agreements/"},{t:"Franchise Law",u:"https://tahmidurrahman.com/franchise-law/"},{t:"Supply Chain Law",u:"https://tahmidurrahman.com/supply-chain-law/"},{t:"Procurement Law",u:"https://tahmidurrahman.com/procurement-law/"},{t:"Consumer Protection",u:"https://tahmidurrahman.com/consumer-protection/"},{t:"Product Liability",u:"https://tahmidurrahman.com/product-liability-law/"},{t:"Competition Law",u:"https://tahmidurrahman.com/competition-law/"},{t:"International Trade",u:"https://tahmidurrahman.com/international-trade/"},{t:"Agency & Representation",u:"https://tahmidurrahman.com/agency-representation/"},{t:"E-Commerce & Digital Contracts",u:"https://tahmidurrahman.com/commercial-agreements/"}],

"international-business":[{t:"Cross-Border Transactions",u:"https://tahmidurrahman.com/cross-border-transactions/"},
{t:"JV Structuring",u:"https://tahmidurrahman.com/jv-structuring/"},
{t:"Technology Transfer",u:"https://tahmidurrahman.com/technology-transfer/"},
{t:"International Arbitration",u:"https://tahmidurrahman.com/international-arbitration/"},
{t:"Free Zone Company Setup (UAE)",u:"https://tahmidurrahman.com/uae-free-zone-company/"},
{t:"Double Tax Treaty Planning",u:"https://tahmidurrahman.com/double-tax-treaty-planning/"},
{t:"International Employment & Mobility",u:"https://tahmidurrahman.com/international-employment-mobility/"},
{t:"International Franchising",u:"https://tahmidurrahman.com/international-franchising/"},
{t:"Foreign Branch & Rep Office",u:"https://tahmidurrahman.com/foreign-branch-rep-office/"},
{t:"FDI Approvals (BIDA)",u:"https://tahmidurrahman.com/fdi-approvals-bida/"},
{t:"Customs & Trade Compliance",u:"https://tahmidurrahman.com/customs-trade-compliance/"},
{t:"Sanctions & Export Controls",u:"https://tahmidurrahman.com/sanctions-export-controls/"},
{t:"Offshore Company Formation",u:"https://tahmidurrahman.com/offshore-company-formation/"},
{t:"Transfer Pricing Advisory",u:"https://tahmidurrahman.com/transfer-pricing-advisory/"},
{t:"Global Data Protection (GDPR)",u:"https://tahmidurrahman.com/gdpr-global-data-protection/"},
{t:"Supply & Distribution in MENA/SAARC",u:"https://tahmidurrahman.com/supply-distribution-in-mena-saarc/"}],
"regulatory-compliance":[
{t:"RJSC Filings & Compliance",u:"https://tahmidurrahman.com/rjsc-fee-calculator-page/"},
{t:"Bangladesh Bank Approvals",u:"https://tahmidurrahman.com/best-banking-law-firm-in-bangladesh-2020-award-global-law-experts-clp/"},
{t:"BSEC Compliance",u:"https://tahmidurrahman.com/corporate-compliance/"},
{t:"NBR Tax & VAT Compliance",u:"https://tahmidurrahman.com/corporate-compliance/"},
{t:"Anti-Money Laundering (AML/CFT)",u:"https://tahmidurrahman.com/substantive-and-interim-remedies-in-bangladesh/"},
{t:"Anti-Bribery & Corruption",u:"https://tahmidurrahman.com/anti-corruption-commission-in-bangladesh/"},
{t:"Competition/Antitrust Compliance",u:"https://tahmidurrahman.com/corporate-compliance/"},
{t:"Data Protection & Privacy",u:"https://tahmidurrahman.com/cybersecurity-data-privacy/"},
{"t":"Environmental & ESG Compliance","u":"https://tahmidurrahman.com/environmental-law-in-bangladesh/"},
{t:"Labour Law Compliance",u:"https://tahmidurrahman.com/employee-rights-labour-law-in-bangladesh/"},
{t:"Import/Export Licensing",u:"https://tahmidurrahman.com/import-and-export-license-in-bangladesh/"},
{"t":"Sectoral Licenses (Telecom/BTRC)","u":"https://tahmidurrahman.com/pstn-licence-in-bangladesh-process-timelines-and-compliances/"},
{t:"BIDA Post-Approval Compliance",u:"https://tahmidurrahman.com/corporate-compliance/"},
{t:"Corporate Investigations",u:"https://tahmidurrahman.com/corporate-compliance/"},
{t:"Whistleblower Programs",u:"https://tahmidurrahman.com/pstn-licence-in-bangladesh-process-timelines-and-compliances/"},
{t:"Compliance Audits & Training",u:"https://tahmidurrahman.com/corporate-compliance/"}
],
"banking-finance":[
{t:"Loan Documentation",u:"https://tahmidurrahman.com/foreign-loans-bangladesh/"},
{t:"Secured Lending & Syndication",u:"https://tahmidurrahman.com/banking-and-finance-litigation/"},
{"t":"Project Finance","u":"https://tahmidurrahman.com/project-development-finance/"},
{"t":"Trade Finance (LCs)","u":"https://tahmidurrahman.com/trade-commodities-and-export-finance/"},
{t:"Islamic Finance",u:"https://tahmidurrahman.com/islamic-finance-in-2025/"},
{t:"Restructuring & Insolvency",u:"https://tahmidurrahman.com/restructuring-and-insolvency-law-firm/"},
{t:"Regulatory (Bangladesh Bank)",u:"https://tahmidurrahman.com/banking-and-finance-litigation-law-firm-in-bangladesh/"},
{t:"NBFI Licensing & Compliance",u:"https://tahmidurrahman.com/nbfi-formation-in-bangladesh/"},
{t:"Microfinance & MFI Compliance",u:"https://tahmidurrahman.com/corporate-compliance/"},
{t:"Derivatives & Repo",u:"https://tahmidurrahman.com/islamic-derivatives-and-structured-finance/"},
{t:"Asset Finance (Aviation/Maritime)",u:"https://tahmidurrahman.com/asset-finance-law-firm-in-bangladesh/"},
{t:"FinTech Payments & PSP Licensing",u:"https://tahmidurrahman.com/fintech-innovations-in-a-globalized-market/"},
{t:"Securitization",u:"https://tahmidurrahman.com/real-estate-finance/"},
{t:"Cross-Border Financing",u:"https://tahmidurrahman.com/payments-trends-and-cross-border-transactions/"},
{t:"Guarantees & Security Perfection",u:"https://tahmidurrahman.com/cybersecurity-threats/"},
{t:"Debt Recovery & Enforcement",u:"https://tahmidurrahman.com/public-demands-recovery-act/"}
],
"investment-law":[
{t:"FDI & Entry Strategy",u:"https://tahmidurrahman.com/fdi-inbound-investment-and-permits/"},
{t:"Investment Structuring",u:"https://tahmidurrahman.com/investment-management-in-bangladesh/"},
{t:"Investment Approvals (BIDA/BEPZA)",u:"https://tahmidurrahman.com/bida-registration-for-foreign-investment/"},
{t:"Bilateral Investment Treaty (BIT) Advice",u:"https://tahmidurrahman.com/outbound-investment-and-citizenship/"},
{t:"Investment Disputes & ICSID",u:"https://tahmidurrahman.com/private-wealth-disputes-in-bangladesh/"},
{t:"Capital Controls & Repatriation",u:"https://tahmidurrahman.com/capital-market-transactions-and-disputes/"},
{t:"Tax Incentives & Zones",u:"https://tahmidurrahman.com/tax-pensions-employment-incentives/"},
{t:"Joint Investment Agreements",u:"https://tahmidurrahman.com/funds-investment-management/"},
{t:"Private Equity & VC Transactions",u:"https://tahmidurrahman.com/private-equity-law-in-bangladesh/"},
{t:"Foreign Portfolio Investment",u:"https://tahmidurrahman.com/procedure-of-foreign-investment-in-bangladesh/"},
{t:"Real Estate Investment Vehicles",u:"https://tahmidurrahman.com/real-estate-business-in-bangladesh/"},
{t:"Fund Formation & Regulation",u:"https://tahmidurrahman.com/funds-investment-management-law-firm-in-bangladesh/"},
{t:"Investment Exit & Divestment",u:"https://tahmidurrahman.com/funds-and-investment-management/"},
{t:"Security & Strategic Review",u:"https://tahmidurrahman.com/cybersecurity-threats/"},
{t:"PPP & Infrastructure Investment",u:"https://tahmidurrahman.com/g2g-ppp-and-infrastructure-projects-in-bangladesh/"},
{t:"Investor-State Arbitration Support",u:"https://tahmidurrahman.com/state-to-state-arbitration-process/"}
],
"equity":[
{t:"IPO & Listing (DSE/CSE)",u:"https://tahmidurrahman.com/issue-management-for-ipo-in-bangladesh/"},
{t:"Rights Issue & Preferential Allotments",u:"https://tahmidurrahman.com/women-rights-against-sexual-violence-in-bangladesh/"},
{"t":"Debt Capital Markets (Bonds, Sukuk)","u":"https://tahmidurrahman.com/debt-capital-markets/"},
{t:"Prospectus & Offering Circulars",u:"https://tahmidurrahman.com/articles/"},
{"t":"Underwriting & Book Building","u":"https://tahmidurrahman.com/issue-management-for-ipo-in-bangladesh/"},
{t:"Listing Compliance (BSEC)",u:"https://tahmidurrahman.com/corporate-compliance/"},
{t:"Takeovers & Public M&A",u:"https://tahmidurrahman.com/administrative-public-law/"},
{t:"Insider Trading & Market Abuse",u:"https://tahmidurrahman.com/emissions-linked-trading-in-the-us-and-eu/"},
{t:"Corporate Governance & Disclosure",u:"https://tahmidurrahman.com/corporate-governance/"},
{t:"ESOPs & Employee Securities",u:"https://tahmidurrahman.com/employee-rights-labour-law-in-bangladesh/"},
{t:"Private Placements",u:"https://tahmidurrahman.com/private-funds/"},
{t:"GDR/ADR Programs",u:"https://tahmidurrahman.com/alternative-dispute-resolution-adr-law-firm-in-bangladesh/"},
{t:"Trustee & Debenture Trust Deed",u:"https://tahmidurrahman.com/charitable-trust-in-bangladesh/"},
{t:"Rating & Compliance Liaison",u:"https://tahmidurrahman.com/liaison-office-in-bangladesh/"},
{t:"Market Intermediaries Licensing",u:"https://tahmidurrahman.com/capital-market-in-bangladesh-in-2023/"},
{t:"Post-Listing Compliance & Reporting",u:"https://tahmidurrahman.com/corporate-compliance/"}
],
"fintech-crypto":[
{t:"PSP/PSO Licensing",u:"https://tahmidurrahman.com/pso-license-in-bangladesh/"},
{t:"Mobile Financial Services (MFS)",u:"https://tahmidurrahman.com/consumer-financial-services/"},
{t:"Payment Gateway Compliance",u:"https://tahmidurrahman.com/lc-payment-and-commercial-dispute-resolution/"},
{t:"Open Banking & APIs",u:"https://tahmidurrahman.com/step-by-step-process-to-open-a-non-banking-financial-institution-nbfi-in-bangladesh/"},
{t:"Digital KYC/AML",u:"https://tahmidurrahman.com/pioneering-innovation-in-the-fintech-sector/"},
{t:"Data Privacy for FinTechs",u:"https://tahmidurrahman.com/cybersecurity-data-privacy/"},
{t:"Cross-Border Remittance Tech",u:"https://tahmidurrahman.com/pioneering-innovation-in-the-fintech-sector/"},
{t:"E-Money & Stored Value",u:"https://tahmidurrahman.com/money-suit-cases-in-bangladesh/"},
{t:"Crypto/Virtual Assets Advisory",u:"https://tahmidurrahman.com/board-advisory/"},
{t:"Tokenization & Digital Securities",u:"https://tahmidurrahman.com/pioneering-innovation-in-the-fintech-sector/"},
{t:"RegTech Implementation",u:"https://tahmidurrahman.com/fintech-law-firm-in-bangladesh/"},
{"t":"Cybersecurity & Incident Response","u":"https://tahmidurrahman.com/cybersecurity-law-in-bangladesh/"},
{t:"Smart Contract Review",u:"https://tahmidurrahman.com/epc-and-om-contracts-in-bangladesh/"},
{t:"Crowdfunding & P2P Lending",u:"https://tahmidurrahman.com/fintech-law-firm-in-bangladesh/"},
{t:"Digital Banking/Neobank Setup",u:"https://tahmidurrahman.com/islamic-banking-and-finance-globally/"},
{t:"Sandbox & Regulatory Engagement",u:"https://tahmidurrahman.com/regulatory-investigations-and-financial-crime/"}
],
"business-immigration":[
{"t":"Work Permits","u":"https://tahmidurrahman.com/form-i-765-and-the-employment-authorization-document-ead-card-explained/"},
{"t":"Employment Visas","u":"https://tahmidurrahman.com/the-h-1b-visa-explained/"},
{"t":"Intra-Company Transfers","u":"https://tahmidurrahman.com/l-1-visa-guide-for-bangladeshi-professionals-and-companies/"},
{"t":"Investor & Entrepreneur Visas","u":"https://tahmidurrahman.com/e-2-visa-explained/"},
{"t":"Business Visit Visas","u":"https://tahmidurrahman.com/b-1-b-2-visitor-visa-guide-2025-trw-law-firm/"},
{"t":"Company Sponsorship","u":"https://tahmidurrahman.com/the-h-1b-visa-explained/"},
{"t":"Extensions & Renewals","u":"https://tahmidurrahman.com/how-to-renew-a-b-1-b-2-tourist-visa/"},
{"t":"Compliance Audits","u":"https://tahmidurrahman.com/preventing-a-request-for-evidence-rfe/"},
{"t":"Global Mobility Policy","u":"https://tahmidurrahman.com/u-s-immigration-explained-a-step-by-step-trw-law-firm-guide-2025-edition/"},
{"t":"Dependants Processing","u":"https://tahmidurrahman.com/cr1-and-ir1-spouse-visas-explained-a-trw-law-firm-guide-to-u-s-spousal-immigration-2025-edition/"},
{"t":"Change of Employer","u":"https://tahmidurrahman.com/the-h-1b-visa-explained/"},
{"t":"Labour Market/Exemptions","u":"https://tahmidurrahman.com/complete-guide-to-the-eb-2-niw-visa/"},
{t:"Visa Appeals & Administrative Review",u:"https://tahmidurrahman.com/civil-appeals-in-bangladesh-in-2024/"},
{t:"Exit Permits & Clearances",u:"https://tahmidurrahman.com/form-i-94-explained-how-the-arrival-departure-record-tracks-u-s-entry-and-exit-and-why-it-matters-2/"},
{t:"Residency by Investment Guidance",u:"https://tahmidurrahman.com/u-s-immigration-explained-a-step-by-step-trw-law-firm-guide-2025-edition/"},
{t:"Country-Specific Packages (UAE/UK etc.)",u:"https://tahmidurrahman.com/specific-performance-of-contract-in-bangladesh/"}
],
"family-immigration":[
{"t":"Spouse & Partner Visas","u":"https://tahmidurrahman.com/cr1-and-ir1-spouse-visas-explained-a-trw-law-firm-guide-to-u-s-spousal-immigration-2025-edition/"},
{"t":"Parent & Child Sponsorship","u":"https://tahmidurrahman.com/complete-guide-to-family-based-immigration/"},
{"t":"Family Reunification","u":"https://tahmidurrahman.com/complete-guide-to-family-based-immigration/"},
{"t":"Marriage-Based Residency","u":"https://tahmidurrahman.com/the-green-card-explained-a-trw-law-firm-guide-to-u-s-permanent-residency-2025-edition/"},
{t:"Adoption & Guardianship Immigration",u:"https://tahmidurrahman.com/advance-parole-in-u-s-immigration/"},
{t:"Humanitarian & Compassionate Grounds",u:"https://tahmidurrahman.com/common-immigration-and-naturalization-forms-and-fees-in-2025/"},
{"t":"Overstay Regularization","u":"https://tahmidurrahman.com/adjustment-of-status-vs-consular-processing-which-path-is-right-for-your-green-card/"},
{"t":"Naturalization Through Marriage","u":"https://tahmidurrahman.com/complete-guide-to-family-based-immigration/"},
{t:"Divorce-Related Status Changes",u:"https://tahmidurrahman.com/divorce-certificate-in-bangladesh/"},
{t:"Domestic Worker Sponsorship",u:"https://tahmidurrahman.com/skilled-worker-visa-in-uk-from-bangladesh/"},
{"t":"Dependent Permits","u":"https://tahmidurrahman.com/how-to-get-a-u-s-tourist-visa-for-your-parents/"},
{t:"DNA & Document Authentication",u:"https://tahmidurrahman.com/heba-will-gift-document-registration-in-bangladesh/"},
{"t":"Translation & Legalization","u":"https://tahmidurrahman.com/what-is-an-affidavit-of-support/"},
{t:"Appeals & Judicial Review",u:"https://tahmidurrahman.com/fundamental-rights-judicial-review-and-writs-in-bangladesh/"},
{t:"Travel Permits for Minors",u:"https://tahmidurrahman.com/fdi-inbound-investment-and-permits-law-firm-in-bangladesh/"},
{t:"Surrogacy-Related Immigration",u:"https://tahmidurrahman.com/surrogacy-law-in-bangladesh-in-2025/"}
],
"investor-visas":[
{"t":"Golden Visas","u":"https://tahmidurrahman.com/obtaining-a-dubai-golden-visa-from-bangladesh/"},
{"t":"Entrepreneur Visas","u":"https://tahmidurrahman.com/e-2-visa-explained/"},
{"t":"Start-up Visas","u":"https://tahmidurrahman.com/e-2-visa-explained/"},
{"t":"Source of Funds & KYC","u":"https://tahmidurrahman.com/avenues-to-receive-currency-from-a-foreign-jurisdiction-in-bangladesh/"},
{"t":"Business Plans & Projections","u":"https://tahmidurrahman.com/startup-funding-process-in-bangladesh/"},
{"t":"Investment Due Diligence","u":"https://tahmidurrahman.com/due-diligence/"},
{"t":"Real Estate Investment Pathways","u":"https://tahmidurrahman.com/outbound-investment-and-citizenship/"},
{"t":"Bank Account & Tax Registration","u":"https://tahmidurrahman.com/opening-a-bank-account-for-a-company-in-bangladesh/"},
{"t":"Family Add-On Processing","u":"https://tahmidurrahman.com/cr1-and-ir1-spouse-visas-explained-a-trw-law-firm-guide-to-u-s-spousal-immigration-2025-edition/"},
{t:"Renewal & Maintenance",u:"https://tahmidurrahman.com/best-us-immigration-law-firm-in-bangladesh/"},
{t:"Exit Strategy & Citizenship Planning",u:"https://tahmidurrahman.com/immigration-and-citizenship-in-bangladesh/"},
{t:"Government Liaison & Appointments",u:"https://tahmidurrahman.com/liaison-office-in-bangladesh/"},
{t:"Health Insurance & Medicals",u:"https://tahmidurrahman.com/healthcare-life-sciences-chemicals/"},
{t:"Police Clearance & Security Screening",u:"https://tahmidurrahman.com/environment-clearance-license-in-bangladesh/"},
{t:"Translation & Notarization",u:"https://tahmidurrahman.com/legal-translation-in-bangladesh/"},
{t:"Appeals & Reconsideration",u:"https://tahmidurrahman.com/civil-and-criminal-appeals-in-high-court-litigation/"}
],
"citizenship-naturalization":[
{t:"Eligibility Assessment",u:"https://tahmidurrahman.com/immigration-and-citizenship-in-bangladesh/"},
{t:"Dual Citizenship Guidance",u:"https://tahmidurrahman.com/immigration-and-citizenship-in-bangladesh/"},
{t:"Citizenship by Descent/Ancestry",u:"https://tahmidurrahman.com/immigration-and-citizenship-in-bangladesh/"},
{t:"Citizenship by Investment Advice",u:"https://tahmidurrahman.com/outbound-investment-and-citizenship/"},
{"t":"Naturalization Applications","u":"https://tahmidurrahman.com/common-immigration-and-naturalization-forms-and-fees-2025-edition/"},
{t:"Oath & Passport Processing",u:"https://tahmidurrahman.com/food-processing-business-registration-in-bangladesh/"},
{"t":"Renunciation & Reacquisition","u":"https://tahmidurrahman.com/ds-4079-explained/"},
{t:"National ID & Registration",u:"https://tahmidurrahman.com/latest-guide-to-company-registration-in-bangladesh/"},
{t:"Name Change & Corrections",u:"https://tahmidurrahman.com/how-to-change-the-name-of-a-company-in-bangladesh-in-2024/"},
{t:"Travel History & Good Character",u:"https://tahmidurrahman.com/how-bangladeshis-with-little-or-no-travel-history-can-get-a-u-s-visa-with-trw-law-firms-expert-guidance/"},
{t:"Legalization & Apostille",u:"https://tahmidurrahman.com/immigration-and-citizenship-in-bangladesh/"},
{t:"Document Retrieval & Archive",u:"https://tahmidurrahman.com/property-documentation-lawyer-in-bangladesh-ensuring-legal-clarity-and-security/"},
{t:"Minor’s Citizenship Applications",u:"https://tahmidurrahman.com/immigration-and-citizenship-in-bangladesh/"},
{t:"Criminal Record Waivers",u:"https://tahmidurrahman.com/criminal-bail-in-district-court-litigation/"},
{t:"Revocation Defense",u:"https://tahmidurrahman.com/immigration-and-citizenship-in-bangladesh/"},
{t:"Appeals & Judicial Review",u:"https://tahmidurrahman.com/fundamental-rights-judicial-review-and-writs-in-bangladesh/"}
],
"real-estate":[
{t:"Title Search & Due Diligence",u:"https://tahmidurrahman.com/due-diligence/"},
{t:"Sale & Purchase Agreements",u:"https://tahmidurrahman.com/definitive-purchase-agreement/"},
{t:"Lease & Tenancy",u:"https://tahmidurrahman.com/real-estate-finance-2/"},
{t:"Mutation & Record Corrections",u:"https://tahmidurrahman.com/mutation-khatian-in-bangladesh/"},
{t:"Land Development Agreements",u:"https://tahmidurrahman.com/real-estate-lawyer-in-bangladesh-your-legal-partner-in-property-development-and-transactions/"},
{"t":"Real Estate Litigation","u":"https://tahmidurrahman.com/real-estate-litigation-law-in-bangladesh/"},
{t:"Apartment Ownership & Deed",u:"https://tahmidurrahman.com/ownership-of-a-land/"},
{t:"Registration & Stamping",u:"https://tahmidurrahman.com/ngo-registration-in-bangladesh/"},
{t:"Mortgage & Charge Creation",u:"https://tahmidurrahman.com/mortgage-loan-in-bangladesh/"},
{t:"Co-operative Housing",u:"https://tahmidurrahman.com/cooperative-society-registration-in-bangladesh/"},
{t:"Land Conversion & Zoning",u:"https://tahmidurrahman.com/planning-and-zoning-land-laws-in-bangladesh/"},
{t:"Building Approvals & Occupancy",u:"https://tahmidurrahman.com/shipbuilding-and-ship-breaking-business-in-bangladesh/"},
{t:"Encroachment & Boundary Disputes",u:"https://tahmidurrahman.com/property-lawyer-in-bangladesh-legal-solutions-for-real-estate-land-disputes/"},
{t:"Real Estate Tax & VAT",u:"https://tahmidurrahman.com/real-estate-private-equity-law-in-bangladesh/"},
{t:"Construction Financing Docs",u:"https://tahmidurrahman.com/real-estate-law-in-bangladesh-law-of-construction-matters-a-complete-overview-of-real-estate-in-bangladesh/"},
{t:"Project Handover & Possession",u:"https://tahmidurrahman.com/project-management-consultancy/"}
],
"property-development":[
{t:"Joint Development Agreements",u:"https://tahmidurrahman.com/project-development-finance/"},
{t:"Power of Attorney Structures",u:"https://tahmidurrahman.com/power-of-attorney-guidelines/"},
{t:"Developer-Buyer Agreements",u:"https://tahmidurrahman.com/shareholder-agreements/"},
{t:"Real Estate Regulatory Compliance",u:"https://tahmidurrahman.com/real-estate-lawyer-in-bangladesh-your-legal-partner-in-property-development-and-transactions/"},
{t:"Project Structuring & SPVs",u:"https://tahmidurrahman.com/project-development-finance-law-firm-in-bangladesh/"},
{t:"Vendor & Contractor Contracts",u:"https://tahmidurrahman.com/epc-and-om-contracts-law-firm-in-bangladesh/"},
{t:"Procurement & Tendering",u:"https://tahmidurrahman.com/project-development-finance/"},
{t:"Environmental Clearances",u:"https://tahmidurrahman.com/environmental-law-in-bangladesh/"},
{t:"Utility Connections & NOCs",u:"https://tahmidurrahman.com/health-nutrition-and-human-development/"},
{t:"Project Insurance",u:"https://tahmidurrahman.com/project-development-finance/"},
{t:"Pre-Sales & Marketing Compliance",u:"https://tahmidurrahman.com/corporate-compliance/"},
{t:"Consumer Complaint Handling",u:"https://tahmidurrahman.com/consumer-goods-retail/"},
{t:"Handover & Defect Liability",u:"https://tahmidurrahman.com/outstanding-liability-position-in-a-bank/"},
{t:"Strata/Condominium Management",u:"https://tahmidurrahman.com/funds-investment-management/"},
{t:"Community By-Laws",u:"https://tahmidurrahman.com/provident-fund-laws/"},
{t:"Dispute Resolution for Developers",u:"https://tahmidurrahman.com/alternative-dispute-resolution-adr/"}
],
"construction-law":[
{t:"EPC & Turnkey Contracts",u:"https://tahmidurrahman.com/epc-and-om-contracts-in-bangladesh/"},
{t:"FIDIC Contracts",u:"https://tahmidurrahman.com/epc-and-om-contracts-in-bangladesh/"},
{t:"Subcontracting Agreements",u:"https://tahmidurrahman.com/shareholder-agreements/"},
{t:"Payment & Variation Claims",u:"https://tahmidurrahman.com/payments-trends-and-cross-border-transactions/"},
{t:"Delay & Disruption",u:"https://tahmidurrahman.com/construction-and-infrastructure-business-in-bangladesh/"},
{t:"Performance Bonds & Guarantees",u:"https://tahmidurrahman.com/specific-performance-of-contract-in-bangladesh/"},
{t:"Health & Safety Compliance",u:"https://tahmidurrahman.com/healthcare-business-in-bangladesh/"},
{t:"Construction Arbitration",u:"https://tahmidurrahman.com/cietac-arbitration-tribunal/"},
{t:"Adjudication & DAB",u:"https://tahmidurrahman.com/construction-and-infrastructure-business-in-bangladesh/"},
{t:"Defects & Warranty Claims",u:"https://tahmidurrahman.com/admiralty-maritime-and-casualty-claims/"},
{t:"Construction Insurance",u:"https://tahmidurrahman.com/insurance/"},
{t:"Building Code Compliance",u:"https://tahmidurrahman.com/shipbuilding-and-ship-breaking-business-in-bangladesh/"},
{t:"Termination & Suspension",u:"https://tahmidurrahman.com/employment-termination-law/"},
{t:"Public Procurement & PPA",u:"https://tahmidurrahman.com/public-policy-practice-at-trw-law-firm/"},
{t:"Contractor Licensing & Blacklisting",u:"https://tahmidurrahman.com/construction-and-infrastructure-business-in-bangladesh/"},
{t:"Dispute Boards & Expert Determination",u:"https://tahmidurrahman.com/land-law-firm-in-bangladesh-trws-expert-solutions-for-land-ownership-disputes-transfers/"}
],
"land-acquisition":[
{t:"Land Vetting & Due Diligence",u:"https://tahmidurrahman.com/due-diligence/"},
{t:"Acquisition for Industry/Infrastructure",u:"https://tahmidurrahman.com/infrastructure/"},
{t:"Government Lease & Khatians",u:"https://tahmidurrahman.com/land-water-and-waste-management-law-firm-in-bangladesh/"},
{t:"Easements & Right of Way",u:"https://tahmidurrahman.com/adjustment-of-status-vs-consular-processing-which-path-is-right-for-your-green-card/"},
{t:"Compensation & Rehabilitation",u:"https://tahmidurrahman.com/compensation-benefits-and-employment/"},
{t:"Land Survey & Demarcation",u:"https://tahmidurrahman.com/land-survey-tribunal-in-2025/"},
{t:"Conversion (Non-Agri/Industrial)",u:"https://tahmidurrahman.com/industrials/"},
{t:"Land Tax & Mutation",u:"https://tahmidurrahman.com/land-trespassing-in-bangladesh/"},
{t:"Title Rectification & Partition",u:"https://tahmidurrahman.com/rectifications-and-amendments-in-company-law/"},
{t:"Acquisition Litigation & Writs",u:"https://tahmidurrahman.com/land-acquisition-in-bangladesh/"},
{t:"Encumbrance Certificate Retrieval",u:"https://tahmidurrahman.com/environmental-clearance-certificate-in-2024/"},
{t:"Land Ceiling & Zoning",u:"https://tahmidurrahman.com/planning-and-zoning-land-laws-in-bangladesh/"},
{t:"Trusts & Wakf Property",u:"https://tahmidurrahman.com/property-law-firm-in-bangladesh-trws-expertise-in-real-estate-land-disputes-legal-solutions/"},
{t:"Special Economic Zone Land",u:"https://tahmidurrahman.com/pre-emption-in-land-law-of-bangladesh/"},
{t:"Deed Drafting & Registration",u:"https://tahmidurrahman.com/partnership-deed-registration-in-bangladesh-in-2023/"},
{t:"Dispute Settlement & ADR",u:"https://tahmidurrahman.com/alternative-dispute-resolution-adr/"}
],
"family-divorce":[
{t:"Uncontested Divorce",u:"https://tahmidurrahman.com/best-divorce-and-family-lawyer-in-dhaka/"},
{t:"Contested Divorce",u:"https://tahmidurrahman.com/best-divorce-and-family-lawyer-in-dhaka/"},
{t:"Dower & Maintenance",u:"https://tahmidurrahman.com/family-law-firm-in-dhaka-bangladesh/"},
{t:"Talaq & Khula (Islamic)",u:"https://tahmidurrahman.com/trw-islamic-inheritance-calculator/"},
{t:"Separation Agreements",u:"https://tahmidurrahman.com/shareholder-agreements/"},
{t:"Domestic Violence & Protection",u:"https://tahmidurrahman.com/women-rights-against-sexual-violence-in-bangladesh/"},
{t:"Interim Relief & Orders",u:"https://tahmidurrahman.com/substantive-and-interim-remedies-in-bangladesh/"},
{t:"Property Division",u:"https://tahmidurrahman.com/supreme-court-of-bd-high-court-division/"},
{t:"Mediation & Settlement",u:"https://tahmidurrahman.com/mediation-in-bangladesh/"},
{t:"Foreign Divorce Recognition",u:"https://tahmidurrahman.com/best-divorce-and-family-lawyer-in-dhaka/"},
{t:"Restitution of Conjugal Rights",u:"https://tahmidurrahman.com/cyber-law-of-bangladesh-internet-law-web-ict-act-rules-regulations-punishment-and-rights-in-bangladesh/"},
{t:"Alimony & Spousal Support",u:"https://tahmidurrahman.com/what-is-an-affidavit-of-support/"},
{t:"Annulment",u:"https://tahmidurrahman.com/function-of-family-court-in-bangladesh/"},
{t:"Child Custody (Interim)",u:"https://tahmidurrahman.com/child-custody-after-divorce-in-bangladesh/"},
{t:"Guardianship Orders",u:"https://tahmidurrahman.com/legal-guardianship-in-bangladesh/"},
{t:"Enforcement of Decrees",u:"https://tahmidurrahman.com/function-of-family-court-in-bangladesh/"}
],
"family-custody":[
{t:"Custody Applications",u:"https://tahmidurrahman.com/how-to-get-child-custody-in-bangladesh-in-2025/"},
{t:"Visitation & Access Orders",u:"https://tahmidurrahman.com/urgent-injunctions-stay-orders-and-status-quo/"},
{t:"Child Support",u:"https://tahmidurrahman.com/child-custody-after-divorce-in-bangladesh/"},
{t:"Relocation & Abduction",u:"https://tahmidurrahman.com/how-to-get-child-custody-in-bangladesh-in-2025/"},
{t:"Guardianship & Wardship",u:"https://tahmidurrahman.com/legal-guardianship-in-bangladesh/"},
{t:"Paternity & DNA Issues",u:"https://tahmidurrahman.com/child-custody-after-divorce-in-bangladesh/"},
{t:"Adoption Procedures",u:"https://tahmidurrahman.com/procedures-to-get-tax-exemption-certificate/"},
{t:"Special Needs Considerations",u:"https://tahmidurrahman.com/bufete-de-abogados-especializado-en-hoteles-hosteleria-y-ocio-en-bangladesh/"},
{t:"Education & Medical Decisions",u:"https://tahmidurrahman.com/medical-negligence/"},
{t:"Enforcement of Orders",u:"https://tahmidurrahman.com/supreme-court-of-bangladesh/"},
{t:"Modification of Orders",u:"https://tahmidurrahman.com/contempt-of-court-in-bangladesh/"},
{t:"Supervised Access",u:"https://tahmidurrahman.com/child-custody-after-divorce-in-bangladesh/"},
{t:"International Custody",u:"https://tahmidurrahman.com/international-and-cross-border-law-firm/"},
{t:"Mediation & Parenting Plans",u:"https://tahmidurrahman.com/mediation-in-bangladesh/"},
{t:"Contempt & Non-Compliance",u:"https://tahmidurrahman.com/contempt-of-court-law-firm-in-bangladesh/"},
{t:"Cross-Border Support Recovery",u:"https://tahmidurrahman.com/international-and-cross-border-law-in-bangladesh/"}
],
"family-matrimonial":[
{t:"Nikahnama & Agreement Drafting",u:"https://tahmidurrahman.com/spa-agreement-in-bangladesh/"},
{t:"Prenuptial & Postnuptial Agreements",u:"https://tahmidurrahman.com/shareholder-agreements/"},
{t:"Marriage Registration",u:"https://tahmidurrahman.com/marriage-green-card-timeline/"},
{t:"Interfaith Marriage Advice",u:"https://tahmidurrahman.com/interfaith-marriages-in-bangladesh-in-2025/"},
{t:"Immigration-Impact Advice",u:"https://tahmidurrahman.com/best-us-immigration-law-firm-in-bangladesh/"},
{t:"Dowry/Stridhan Claims",u:"https://tahmidurrahman.com/debt-and-claims-trading-in-bangladesh/"},
{t:"Domestic Abuse Remedies",u:"https://tahmidurrahman.com/land-grabbing-remedies/"},
{t:"Nullity & Annulment",u:"https://tahmidurrahman.com/articles/"},
{t:"Restitution of Conjugal Rights",u:"https://tahmidurrahman.com/cyber-law-of-bangladesh-internet-law-web-ict-act-rules-regulations-punishment-and-rights-in-bangladesh/"},
{t:"Conjugal Rights Enforcement",u:"https://tahmidurrahman.com/business-and-human-rights-law-firm/"},
{t:"Inheritance & Dower Planning",u:"https://tahmidurrahman.com/inheritance-law-in-bangladesh/"},
{t:"Succession Certificates",u:"https://tahmidurrahman.com/warisan-certificate/"},
{t:"Maintenance & Alimony",u:"https://tahmidurrahman.com/articles/"},
{t:"Bigamy/Polygamy Regulations",u:"https://tahmidurrahman.com/trade-mark-laws-and-regulations-bangladesh/"},
{t:"Marital Property Regimes",u:"https://tahmidurrahman.com/intellectual-property-in-2025/"},
{t:"Marriage Counseling & ADR",u:"https://tahmidurrahman.com/alternative-dispute-resolution-adr/"}
],
"family-international":[
{t:"Cross-Border Divorce Strategy",u:"https://tahmidurrahman.com/payments-trends-and-cross-border-transactions/"},
{t:"Choice of Law & Forum",u:"https://tahmidurrahman.com/list-of-law-firm-in-bangladesh/"},
{t:"Child Abduction (Hague) Advice",u:"https://tahmidurrahman.com/child-student-visa-in-uk/"},
{t:"International Maintenance Claims",u:"https://tahmidurrahman.com/international-trade-law-in-bangladesh/"},
{t:"Recognition & Enforcement (exequatur)",u:"https://tahmidurrahman.com/articles/"},
{t:"Prenups for Expats",u:"https://tahmidurrahman.com/expats-and-employment-law-in-bangladesh/"},
{t:"Surrogacy & ART Cross-border",u:"https://tahmidurrahman.com/insolvency-international-trade-and-cross-border/"},
{t:"Relocation Disputes",u:"https://tahmidurrahman.com/international-arbitration-disputes-in-bangladesh/"},
{t:"International Adoption",u:"https://tahmidurrahman.com/international-finance-and-asset-based-solutions/"},
{t:"Interpol/Immigration Holds",u:"https://tahmidurrahman.com/complete-guide-to-family-based-immigration/"},
{t:"Habitual Residence Analysis",u:"https://tahmidurrahman.com/residence-permit-in-uk/"},
{t:"Consular Liaison Support",u:"https://tahmidurrahman.com/liaison-office-in-bangladesh/"},
{t:"Mirror Orders",u:"https://tahmidurrahman.com/urgent-injunctions-stay-orders-and-status-quo/"},
{t:"Protective/Risk Orders Internationally",u:"https://tahmidurrahman.com/urgent-injunctions-stay-orders-and-status-quo/"},
{t:"Mediation via Video/Remote",u:"https://tahmidurrahman.com/mediation-in-bangladesh/"},
{t:"Asset Tracing Internationally",u:"https://tahmidurrahman.com/asset-finance-law-firm-in-bangladesh/"}
],
"adr-arbitration":[
{t:"Domestic Arbitration",u:"https://tahmidurrahman.com/cietac-arbitration-tribunal/"},
{t:"International Arbitration (SIAC/ICC/LCIA/CIETAC)",u:"https://tahmidurrahman.com/international-arbitration-disputes-in-bangladesh/"},
{t:"Construction & Infrastructure Arbitration",u:"https://tahmidurrahman.com/construction-and-infrastructure-business-in-bangladesh/"},
{t:"Energy & Natural Resources Arbitration",u:"https://tahmidurrahman.com/energy-and-resources/"},
{t:"Investment Treaty Arbitration",u:"https://tahmidurrahman.com/state-to-state-arbitration-process/"},
{t:"Emergency Arbitrator Relief",u:"https://tahmidurrahman.com/emergency-law-curfew-and-section-144-in-bangladesh/"},
{t:"Interim Measures & Security",u:"https://tahmidurrahman.com/substantive-and-interim-remedies-in-bangladesh/"},
{t:"Enforcement & Set Aside",u:"https://tahmidurrahman.com/setting-up-a-tea-estate-in-bangladesh/"},
{t:"Appointment of Arbitrator",u:"https://tahmidurrahman.com/how-to-book-an-appointment-with-trw-law-firm/"},
{t:"Evidence & Discovery",u:"https://tahmidurrahman.com/admission-in-evidence-act-of-bangladesh/"},
{t:"Expert Witness Management",u:"https://tahmidurrahman.com/private-equity-expertise-by-trw-law-firm/"},
{t:"Arbitration Clauses & Seat Strategy",u:"https://tahmidurrahman.com/arbitration-in-bangladesh-webinar/"},
{t:"Third-Party Funding Advice",u:"https://tahmidurrahman.com/startup-funding-process-in-bangladesh/"},
{t:"Costs & Fees Management",u:"https://tahmidurrahman.com/property-registration-fees-in-bangladesh/"},
{t:"Arbitrator Challenges",u:"https://tahmidurrahman.com/arbitration-in-bangladesh/"},
{t:"Med-Arb & Hybrid Processes",u:"https://tahmidurrahman.com/arbitration-process-in-bangladesh/"}
],
"adr-mediation":[
{t:"Commercial Mediation",u:"https://tahmidurrahman.com/corporate-commercial-transactions-outsourcing/"},
{t:"Family Mediation",u:"https://tahmidurrahman.com/complete-guide-to-family-based-immigration/"},
{t:"Workplace Mediation",u:"https://tahmidurrahman.com/mediation-in-bangladesh/"},
{t:"Court-Annexed Mediation",u:"https://tahmidurrahman.com/inherent-power-of-the-court-under-section-151/"},
{t:"Pre-litigation Mediation",u:"https://tahmidurrahman.com/group-litigation-and-class-actions/"},
{t:"Multi-Party Mediation",u:"https://tahmidurrahman.com/mediation-in-bangladesh/"},
{t:"Online Mediation (ODR)",u:"https://tahmidurrahman.com/online-company-registration-in-bangladesh/"},
{t:"Mediated Settlement Agreements",u:"https://tahmidurrahman.com/shareholder-agreements/"},
{t:"Mediator Training & Coaching",u:"https://tahmidurrahman.com/mediation-in-bangladesh/"},
{t:"Mediation Clauses Drafting",u:"https://tahmidurrahman.com/mediation-in-bangladesh/"},
{t:"Confidentiality & Privilege",u:"https://tahmidurrahman.com/mediation-in-bangladesh/"},
{t:"Cross-Border Mediation",u:"https://tahmidurrahman.com/payments-trends-and-cross-border-transactions/"},
{t:"Mediation in Construction Disputes",u:"https://tahmidurrahman.com/mediation-in-bangladesh/"},
{t:"Banking & Finance Mediation",u:"https://tahmidurrahman.com/banking-and-finance-litigation/"},
{t:"Investor-State Mediation",u:"https://tahmidurrahman.com/mediation-in-bangladesh/"},
{t:"Post-Dispute Facilitation",u:"https://tahmidurrahman.com/litigation-and-dispute-resolution/"}
],
"adr-conciliation":[
{t:"Statutory Conciliation",u:"https://tahmidurrahman.com/articles/"},
{t:"Industrial Disputes Conciliation",u:"https://tahmidurrahman.com/industrials/"},
{t:"Consumer Disputes Conciliation",u:"https://tahmidurrahman.com/consumer-goods-retail/"},
{t:"Public Sector Conciliation",u:"https://tahmidurrahman.com/public-limited-company-in-bangladesh/"},
{t:"Financial Dispute Conciliation",u:"https://tahmidurrahman.com/financial-regulation-services/"},
{t:"Telecom & ICT Conciliation",u:"https://tahmidurrahman.com/telecommunications-media-technology/"},
{t:"Healthcare Conciliation",u:"https://tahmidurrahman.com/healthcare-life-sciences-chemicals/"},
{t:"Insurance Conciliation",u:"https://tahmidurrahman.com/insurance-law-firm-in-bangladesh/"},
{t:"Workplace/Employment Conciliation",u:"https://tahmidurrahman.com/employment-termination-law/"},
{t:"Land & Property Conciliation",u:"https://tahmidurrahman.com/property-lawyer-in-bangladesh-legal-solutions-for-real-estate-land-disputes/"},
{t:"Mediation vs Conciliation Advisory",u:"https://tahmidurrahman.com/mediation-in-bangladesh/"},
{t:"Online Conciliation",u:"https://tahmidurrahman.com/online-news-portal-registration/"},
{t:"Multi-Stakeholder Conciliation",u:"https://tahmidurrahman.com/articles/"},
{t:"Government Liaison & Settlement",u:"https://tahmidurrahman.com/liaison-office-in-bangladesh/"},
{t:"Settlement Drafting & Deeds",u:"https://tahmidurrahman.com/articles/"},
{t:"Enforcement of Settlements",u:"https://tahmidurrahman.com/k-2-visa-for-children-of-us-citizens/"}
],
"adr-other":[
{t:"Negotiation Strategy",u:"https://tahmidurrahman.com/alternative-dispute-resolution-adr/"},
{t:"Early Neutral Evaluation",u:"https://tahmidurrahman.com/alternative-dispute-resolution-adr/"},
{t:"Expert Determination",u:"https://tahmidurrahman.com/private-equity-expertise-by-trw-law-firm/"},
{t:"Dispute Adjudication Boards",u:"https://tahmidurrahman.com/alternative-dispute-resolution-adr/"},
{t:"Mini-Trial / Executive Tribunal",u:"https://tahmidurrahman.com/administrative-and-public-law-firm-in-bangladesh/"},
{t:"Med-Arb & Arb-Med",u:"https://tahmidurrahman.com/carbon-markets/"},
{t:"Facilitation & Consensus Building",u:"https://tahmidurrahman.com/shipbuilding-and-ship-breaking-business-in-bangladesh/"},
{t:"ODR Platforms & Protocols",u:"https://tahmidurrahman.com/alternative-dispute-resolution-adr-law-firm-in-bangladesh/"},
{t:"Ombudsman Schemes",u:"https://tahmidurrahman.com/alternative-dispute-resolution-adr-law-firm-in-bangladesh/"},
{t:"Restorative Justice",u:"https://tahmidurrahman.com/alternative-dispute-resolution-adr/"},
{t:"Community Dispute Resolution",u:"https://tahmidurrahman.com/alternative-dispute-resolution-adr/"},
{t:"Settlement Conferences",u:"https://tahmidurrahman.com/alternative-dispute-resolution-adr-law-firm-in-bangladesh/"},
{t:"Conciliation-Arbitration Hybrids",u:"https://tahmidurrahman.com/cietac-arbitration-tribunal/"},
{t:"Conflict Coaching",u:"https://tahmidurrahman.com/land-dispute-lawyer-in-bangladesh-trw-law-firms-proven-legal-solutions-for-complex-land-conflicts/"},
{t:"Multi-Tier Dispute Clauses",u:"https://tahmidurrahman.com/alternative-dispute-resolution-adr/"},
{t:"ADR Training & Workshops",u:"https://tahmidurrahman.com/alternative-dispute-resolution-adr-law-firm-in-bangladesh/"}
],
"criminal-domestic":[
{t:"FIR & Complaint Drafting",u:"https://tahmidurrahman.com/best-law-firm-in-dhaka/"},
{t:"Anticipatory & Regular Bail",u:"https://tahmidurrahman.com/anticipatory-bail-process-in-bangladesh/"},
{t:"Quashment & Discharge",u:"https://tahmidurrahman.com/561a-quashment-proceedings-in-high-court-in-bangladesh/"},
{t:"Trial Defense",u:"https://tahmidurrahman.com/camera-trial-in-bangladesh/"},
{t:"Appeals & Revisions",u:"https://tahmidurrahman.com/civil-and-criminal-appeals-in-high-court-litigation/"},
{t:"Cybercrime Defense",u:"https://tahmidurrahman.com/cybersecurity-and-cybercrime-law-in-bangladesh/"},
{t:"Financial/White-Collar Offenses",u:"https://tahmidurrahman.com/white-paper-on-the-state-of-the-bangladesh-economy/"},
{t:"Narcotics & Special Laws",u:"https://tahmidurrahman.com/witness-protection-laws/"},
{t:"Domestic Violence Cases",u:"https://tahmidurrahman.com/women-rights-against-sexual-violence-in-bangladesh/"},
{t:"Sexual Offenses Defense",u:"https://tahmidurrahman.com/women-rights-against-sexual-violence-in-bangladesh/"},
{t:"Juvenile Justice",u:"https://tahmidurrahman.com/civil-and-criminal-revision/"},
{t:"Prison & Parole Matters",u:"https://tahmidurrahman.com/advance-parole-in-u-s-immigration/"},
{t:"Victim Representation",u:"https://tahmidurrahman.com/civil-and-criminal-revision/"},
{t:"Witness Protection",u:"https://tahmidurrahman.com/witness-protection-laws/"},
{t:"Forensic & Electronic Evidence",u:"https://tahmidurrahman.com/electronics-company-formation-in-bangladesh/"},
{"t":"Writs & Constitutional Remedies","u":"https://tahmidurrahman.com/writ-petitions-against-tribunals/"}
],
"criminal-international":[
{t:"Extradition & Mutual Legal Assistance",u:"https://tahmidurrahman.com/extortion-cases-in-bangladesh-in-2024-trial-process-and-legal-assistance/"},
{t:"Interpol Red Notices",u:"https://tahmidurrahman.com/regulations-of-microcredit-financial-institutions-in-bangladesh/"},
{t:"War Crimes & Crimes Against Humanity",u:"https://tahmidurrahman.com/financial-crimes-and-negligence-law/"},
{t:"Sanctions & Export Control Violations",u:"https://tahmidurrahman.com/guide-to-export-from-bangladesh-as-a-foreign-investor/"},
{t:"Cross-Border Asset Freezes",u:"https://tahmidurrahman.com/international-and-cross-border-law-firm/"},
{t:"Human Trafficking Defense",u:"https://tahmidurrahman.com/business-human-rights-law/"},
{t:"Terrorism Allegations",u:"https://tahmidurrahman.com/articles/"},
{t:"International Prisoner Transfer",u:"https://tahmidurrahman.com/the-l-1-visa-intracompany-transferee-visa/"},
{t:"Diplomatic Immunities & Privileges",u:"https://tahmidurrahman.com/articles/"},
{t:"ICC & Tribunal Liaison",u:"https://tahmidurrahman.com/land-survey-tribunal-law-firm-in-bangladesh/"},
{t:"Evidence Gathering Abroad",u:"https://tahmidurrahman.com/admission-in-evidence-act-of-bangladesh/"},
{t:"Cooperation with Foreign Counsel",u:"https://tahmidurrahman.com/ngo-registration-guide-for-locals-and-foreigners/"},
{t:"Transfer of Proceedings",u:"https://tahmidurrahman.com/share-transfer-process-of-a-company/"},
{t:"Witness Depositions Overseas",u:"https://tahmidurrahman.com/witness-protection-laws/"},
{t:"Appeals in International Fora",u:"https://tahmidurrahman.com/civil-and-criminal-appeals-in-high-court-litigation/"},
{t:"Universal Jurisdiction Strategy",u:"https://tahmidurrahman.com/avenues-to-receive-currency-from-a-foreign-jurisdiction-in-bangladesh/"}
],
"criminal-corporate":[
{t:"Corporate Fraud & Embezzlement",u:"https://tahmidurrahman.com/public-investment-embezzlement-and-the-state-of-the-economy/"},
{t:"Anti-Bribery & Corruption",u:"https://tahmidurrahman.com/anti-corruption-commission-in-bangladesh/"},
{t:"Money Laundering (AML/CFT)",u:"https://tahmidurrahman.com/money-suit-cases-in-bangladesh/"},
{t:"Tax Evasion Prosecutions",u:"https://tahmidurrahman.com/tax-pensions-employment-incentives/"},
{t:"Securities & Insider Trading",u:"https://tahmidurrahman.com/emissions-linked-trading-in-the-us-and-eu/"},
{t:"Competition Cartels & Dawn Raids",u:"https://tahmidurrahman.com/articles/"},
{t:"Environmental Crimes",u:"https://tahmidurrahman.com/environmental-law-in-bangladesh/"},
{t:"Occupational Safety Prosecutions",u:"https://tahmidurrahman.com/articles/"},
{t:"Banking Offenses",u:"https://tahmidurrahman.com/islamic-banking-law-firm-in-bangladesh/"},
{t:"Cybersecurity Breach Liability",u:"https://tahmidurrahman.com/cybersecurity-threats/"},
{t:"Data Privacy Violations",u:"https://tahmidurrahman.com/cybersecurity-data-privacy/"},
{t:"Product Safety/Recall Crimes",u:"https://tahmidurrahman.com/how-to-source-products-for-your-business-in-bangladesh/"},
{t:"Customs & Import Violations",u:"https://tahmidurrahman.com/import-of-pesticide-license/"},
{t:"Food & Drug Offenses",u:"https://tahmidurrahman.com/arrest-warrants-issued-by-pure-food-courts-in-bangladesh/"},
{t:"Corporate Manslaughter",u:"https://tahmidurrahman.com/corporate-law-firm/"},
{t:"Internal Investigations & Dawn Raid Response",u:"https://tahmidurrahman.com/regulatory-investigations-and-financial-crime-law-firm-in-bangladesh/"}
],
"criminal-compliance":[
{t:"Compliance Program Design",u:"https://tahmidurrahman.com/corporate-compliance/"},
{t:"AML/CFT Programs",u:"https://tahmidurrahman.com/suspense-account-in-bangladesh/"},
{t:"ABC & Gifts/Hospitality Policies",u:"https://tahmidurrahman.com/hotels-hospitality-leisure-law-firm-in-bangladesh/"},
{t:"Dawn Raid Preparedness",u:"https://tahmidurrahman.com/foreign-currency-account-in-bangladesh/"},
{t:"Whistleblower Mechanisms",u:"https://tahmidurrahman.com/bank-account-for-a-company-in-bangladesh/"},
{t:"Sanctions & Trade Controls",u:"https://tahmidurrahman.com/international-trade-law-firm-in-bangladesh/"},
{t:"KYC & Customer Due Diligence",u:"https://tahmidurrahman.com/due-diligence/"},
{t:"Cybersecurity & Incident Plans",u:"https://tahmidurrahman.com/cybersecurity-law-in-bangladesh/"},
{t:"Data Privacy Compliance",u:"https://tahmidurrahman.com/cybersecurity-data-privacy/"},
{t:"Health & Safety Programs",u:"https://tahmidurrahman.com/healthcare-life-sciences-chemicals/"},
{t:"Environmental Compliance",u:"https://tahmidurrahman.com/environmental-law-in-bangladesh/"},
{t:"Competition Compliance",u:"https://tahmidurrahman.com/corporate-compliance/"},
{t:"Financial Services Compliance",u:"https://tahmidurrahman.com/consumer-financial-services/"},
{t:"Third-Party Risk Management",u:"https://tahmidurrahman.com/land-water-and-waste-management-in-bangladesh/"},
{t:"Training & Audits",u:"https://tahmidurrahman.com/opening-a-bank-account-for-a-company-in-bangladesh/"},
{t:"Remediation & Monitorships",u:"https://tahmidurrahman.com/corporate-lawyers-in-bangladesh-your-legal-architects-for-business-success/"}
],
"ip-domestic":[
{"t":"Trademark Registration & Prosecution","u":"https://tahmidurrahman.com/how-to-register-a-trademark-in-bangladesh/"},
{t:"Patent Filing & Prosecution",u:"https://tahmidurrahman.com/charter-shipping-contract-in-bangladesh/"},
{t:"Industrial Design Registration",u:"https://tahmidurrahman.com/partnership-deed-registration-in-bangladesh-in-2023/"},
{t:"Copyright Registration",u:"https://tahmidurrahman.com/partnership-deed-registration-in-bangladesh-in-2023/"},
{t:"IP Searches & Clearance",u:"https://tahmidurrahman.com/partnership-business-in-bangladesh/"},
{t:"Office Actions & Hearings",u:"https://tahmidurrahman.com/branch-office-registration-in-bangladesh/"},
{t:"IP Licensing & Assignments",u:"https://tahmidurrahman.com/proprietorship-business-in-bangladesh/"},
{t:"IP Watch & Portfolio Management",u:"https://tahmidurrahman.com/issue-management-for-ipo-in-bangladesh/"},
{t:"Customs Recordal",u:"https://tahmidurrahman.com/anticipatory-bail-in-high-court-litigation-in-bangladesh/"},
{t:"Opposition & Cancellation",u:"https://tahmidurrahman.com/process-of-share-certificate-cancellation/"},
{t:"Domain Name Disputes (.bd)",u:"https://tahmidurrahman.com/land-law-firm-in-bangladesh-trws-expert-solutions-for-land-ownership-disputes-transfers/"},
{t:"Trade Secret Protection",u:"https://tahmidurrahman.com/trade-license-process-in-bangladesh/"},
{t:"IP Due Diligence",u:"https://tahmidurrahman.com/due-diligence/"},
{t:"IP Valuation",u:"https://tahmidurrahman.com/business-valuation/"},
{t:"IP Audits & Compliance",u:"https://tahmidurrahman.com/corporate-compliance/"},
{t:"Technology Transfer Agreements",u:"https://tahmidurrahman.com/how-to-transfer-business-ownership-in-bangladesh/"}
],
"ip-international":[
{t:"Madrid Protocol Filing",u:"https://tahmidurrahman.com/basis-membership-process-in-2025/"},
{t:"PCT Patent Strategy",u:"https://tahmidurrahman.com/sourcing-public-private-partnership-ppp-projects-in-bangladesh/"},
{t:"Hague Designs",u:"https://tahmidurrahman.com/maritime-laws-of-bangladesh-admiralty-ship-arrest/"},
{t:"WIPO Recordals",u:"https://tahmidurrahman.com/ownership-of-a-land/"},
{t:"Cross-Border Licensing",u:"https://tahmidurrahman.com/payments-trends-and-cross-border-transactions/"},
{t:"Global IP Portfolio Management",u:"https://tahmidurrahman.com/issue-management-for-ipo-in-bangladesh/"},
{t:"International IP Enforcement",u:"https://tahmidurrahman.com/immigration-and-citizenship-in-bangladesh/"},
{t:"Customs & Border Measures",u:"https://tahmidurrahman.com/insolvency-international-trade-and-cross-border-law-firm-in-bangladesh/"},
{t:"Parallel Import Strategy",u:"https://tahmidurrahman.com/import-of-pesticide-license/"},
{t:"International Copyright Strategy",u:"https://tahmidurrahman.com/international-trade-law-in-bangladesh/"},
{t:"Freedom-to-Operate Opinions",u:"https://tahmidurrahman.com/how-to-get-bgmea-membership-in-bangladesh/"},
{t:"IP in M&A Transactions",u:"https://tahmidurrahman.com/shipping-law-firm-in-dhaka-bangladesh/"},
{t:"Export Control & IP",u:"https://tahmidurrahman.com/charter-shipping-contract-in-bangladesh/"},
{t:"Open-Source Compliance",u:"https://tahmidurrahman.com/how-to-open-a-company-in-bangladesh/"},
{t:"Data/Software Licensing",u:"https://tahmidurrahman.com/software-business-in-bangladesh/"},
{t:"Standard-Essential Patents",u:"https://tahmidurrahman.com/quality-certification-and-standard-mark-in-bangladesh/"}
],
"ip-enforcement":[
{t:"Cease & Desist Notices",u:"https://tahmidurrahman.com/how-to-enforce-foreign-law-in-bangladesh-in-2024/"},
{t:"Civil Infringement Suits",u:"https://tahmidurrahman.com/non-appearance-of-parties-in-civil-suits/"},
{t:"Criminal Raids & Seizures",u:"https://tahmidurrahman.com/criminal-petition-cases-in-district-court-litigation-in-bangladesh/"},
{t:"Anton Piller & Mareva Relief",u:"https://tahmidurrahman.com/partnership-deed-registration-in-bangladesh-in-2023/"},
{t:"Customs Seizure Actions",u:"https://tahmidurrahman.com/due-diligence-share-acquisition-and-corporate-transactions/"},
{t:"Online Anti-Counterfeiting",u:"https://tahmidurrahman.com/anticipatory-bail-in-high-court-litigation-in-bangladesh/"},
{t:"Administrative Complaints",u:"https://tahmidurrahman.com/administrative-public-law/"},
{t:"ADR for IP Disputes",u:"https://tahmidurrahman.com/land-law-firm-in-bangladesh-trws-expert-solutions-for-land-ownership-disputes-transfers/"},
{t:"Evidence Preservation",u:"https://tahmidurrahman.com/preventing-a-request-for-evidence-rfe/"},
{t:"Border Enforcement Strategy",u:"https://tahmidurrahman.com/payments-trends-and-cross-border-transactions/"},
{t:"Damages & Account of Profits",u:"https://tahmidurrahman.com/registration-laws-and-regulations-for-for-profit-companies-in-bangladesh/"},
{t:"Domain & Social Media Takedowns",u:"https://tahmidurrahman.com/telecommunications-media-technology/"},
{t:"Trade Dress & Passing Off",u:"https://tahmidurrahman.com/trademark-registration-in-bangladesh/"},
{t:"ISP Liability Management",u:"https://tahmidurrahman.com/land-law-firm-in-bangladesh-trws-expert-solutions-for-land-ownership-disputes-transfers/"},
{t:"Settlement Negotiations",u:"https://tahmidurrahman.com/outbound-investment-and-citizenship/"},
{t:"Post-Judgment Enforcement",u:"https://tahmidurrahman.com/issue-management-for-ipo-in-bangladesh/"}
],
"ip-licensing":[
{t:"Software & SaaS Licensing",u:"https://tahmidurrahman.com/lawkit-saas-application-by-zuttle/"},
{t:"Patent & Know-How Licensing",u:"https://tahmidurrahman.com/how-to-transfer-business-ownership-in-bangladesh/"},
{t:"Trademark Franchising",u:"https://tahmidurrahman.com/sourcing-public-private-partnership-ppp-projects-in-bangladesh/"},
{t:"Joint Development Agreements",u:"https://tahmidurrahman.com/project-development-finance/"},
{t:"Research Collaboration",u:"https://tahmidurrahman.com/sourcing-public-private-partnership-ppp-projects-in-bangladesh/"},
{t:"University Tech Transfer",u:"https://tahmidurrahman.com/land-law-firm-in-bangladesh-trws-expert-solutions-for-land-ownership-disputes-transfers/"},
{t:"Open-Source Licensing",u:"https://tahmidurrahman.com/tax-deduction-at-source-tds-in-bangladesh/"},
{t:"Data Sharing & Monetization",u:"https://tahmidurrahman.com/real-estate-data-analytics-in-bangladesh/"},
{t:"Cloud & Hosting Agreements",u:"https://tahmidurrahman.com/sourcing-public-private-partnership-ppp-projects-in-bangladesh/"},
{t:"OEM & Distribution Agreements",u:"https://tahmidurrahman.com/sourcing-public-private-partnership-ppp-projects-in-bangladesh/"},
{t:"Royalty & Audit Programs",u:"https://tahmidurrahman.com/sourcing-public-private-partnership-ppp-projects-in-bangladesh/"},
{t:"Standard-Setting & FRAND",u:"https://tahmidurrahman.com/sourcing-public-private-partnership-ppp-projects-in-bangladesh/"},
{t:"Cross-Licensing & Pools",u:"https://tahmidurrahman.com/payments-trends-and-cross-border-transactions/"},
{t:"Spin-outs & IP Carve-outs",u:"https://tahmidurrahman.com/sourcing-public-private-partnership-ppp-projects-in-bangladesh/"},
{t:"IP Holding Companies",u:"https://tahmidurrahman.com/holding-and-subsidiary-companies-in-bangladesh/"},
{t:"Technology Escrow & Source Code",u:"https://tahmidurrahman.com/vat-deductible-at-source-in-bangladesh/"}
],
"corporate-tax": [{t:"Corporate Income Tax Advisory",u:"https://tahmidurrahman.com/placeholder/tax/cit-advisory"},{t:"Tax Structuring & Entity Classification",u:"https://tahmidurrahman.com/placeholder/tax/structuring"},{t:"Withholding Tax Planning",u:"https://tahmidurrahman.com/placeholder/tax/withholding"},{t:"Tax Incentives (SEZ/EPZ)",u:"https://tahmidurrahman.com/placeholder/tax/incentives-sez-epz"},{t:"Capital Gains Tax Planning",u:"https://tahmidurrahman.com/placeholder/tax/capital-gains"},{t:"Tax Due Diligence (M&A)",u:"https://tahmidurrahman.com/placeholder/tax/mna-due-diligence"},{t:"Group Tax & Consolidation",u:"https://tahmidurrahman.com/placeholder/tax/group-tax"},{t:"Thin Capitalization Rules",u:"https://tahmidurrahman.com/placeholder/tax/thin-cap"},{t:"Permanent Establishment Analysis",u:"https://tahmidurrahman.com/placeholder/tax/permanent-establishment"},{t:"Tax Residency Certificates",u:"https://tahmidurrahman.com/placeholder/tax/tax-residency"},{t:"Dividend/Interest/Royalty WHT",u:"https://tahmidurrahman.com/placeholder/tax/withholding-dividend-royalty"},{t:"Employment Tax & Payroll Structuring",u:"https://tahmidurrahman.com/placeholder/tax/payroll"},{t:"Tax Computation & Return Review",u:"https://tahmidurrahman.com/placeholder/tax/return-review"},{t:"Tax Risk Management & Governance",u:"https://tahmidurrahman.com/placeholder/tax/governance"},{t:"Advance Rulings & Clarifications",u:"https://tahmidurrahman.com/placeholder/tax/advance-ruling"},{t:"Tax Compliance Calendar & Filings",u:"https://tahmidurrahman.com/placeholder/tax/compliance-calendar"}],
"indirect-tax": [{t:"VAT Registration (BIN)",u:"https://tahmidurrahman.com/placeholder/vat/registration-bin"},{t:"VAT Advisory & Return Filing",u:"https://tahmidurrahman.com/placeholder/vat/returns-compliance"},{t:"Customs Classification & Valuation",u:"https://tahmidurrahman.com/placeholder/customs/classification-valuation"},{t:"Supplementary Duty Analysis",u:"https://tahmidurrahman.com/placeholder/vat/supplementary-duty"},{t:"Excise Duty Advisory",u:"https://tahmidurrahman.com/placeholder/excise/overview"},{t:"VAT Credits & Refunds",u:"https://tahmidurrahman.com/placeholder/vat/refunds-credits"},{t:"VAT on Digital Services",u:"https://tahmidurrahman.com/placeholder/vat/digital-services"},{t:"Withholding VAT / VDS",u:"https://tahmidurrahman.com/placeholder/vat/withholding-vat"},{t:"Bonded Warehouse & Exemptions",u:"https://tahmidurrahman.com/placeholder/customs/bonded-warehouse"},{t:"Advance Income Tax at Import",u:"https://tahmidurrahman.com/placeholder/customs/advance-tax-import"},{t:"HS Code Determination",u:"https://tahmidurrahman.com/placeholder/customs/hs-code"},{t:"Rules of Origin & FTAs",u:"https://tahmidurrahman.com/placeholder/customs/rules-of-origin"},{t:"Sectoral Regimes (Telecom/FS)",u:"https://tahmidurrahman.com/placeholder/vat/special-sectors"},{t:"VAT Audit Assistance",u:"https://tahmidurrahman.com/placeholder/vat/audit-defense"},{t:"Indirect Tax Health Check",u:"https://tahmidurrahman.com/placeholder/indirect/health-check"},{t:"Indirect Tax Automation & Systems",u:"https://tahmidurrahman.com/placeholder/indirect/automation"}],
"international-tax": [{t:"Transfer Pricing Documentation",u:"https://tahmidurrahman.com/placeholder/intl/transfer-pricing-docs"},{t:"Advance Pricing Agreements (APA)",u:"https://tahmidurrahman.com/placeholder/intl/apa"},{t:"Country-by-Country Reporting",u:"https://tahmidurrahman.com/placeholder/intl/cbcr"},{t:"Treaty Relief & DTA Interpretation",u:"https://tahmidurrahman.com/placeholder/intl/treaty-dta"},{t:"PE & Profit Attribution",u:"https://tahmidurrahman.com/placeholder/intl/pe-attribution"},{t:"Cross-Border Financing & Thin Cap",u:"https://tahmidurrahman.com/placeholder/intl/cross-border-financing"},{t:"Anti-Avoidance & GAAR",u:"https://tahmidurrahman.com/placeholder/intl/anti-avoidance"},{t:"Pillar Two & Global Minimum Tax",u:"https://tahmidurrahman.com/placeholder/intl/pillar-2"},{t:"Digital Services Tax",u:"https://tahmidurrahman.com/placeholder/intl/digital-services-tax"},{t:"Royalty/FTS Characterization",u:"https://tahmidurrahman.com/placeholder/intl/royalty-fts"},{t:"Inbound/Outbound Holding Structures",u:"https://tahmidurrahman.com/placeholder/intl/holding-structures"},{t:"IP & Intangibles Migration",u:"https://tahmidurrahman.com/placeholder/intl/ip-migration"},{t:"Exit Tax & Repatriation Planning",u:"https://tahmidurrahman.com/placeholder/intl/exit-tax-repatriation"},{t:"Foreign Tax Credit Optimization",u:"https://tahmidurrahman.com/placeholder/intl/foreign-tax-credits"},{t:"Non-Resident Withholding Compliance",u:"https://tahmidurrahman.com/placeholder/intl/nr-withholding"},{t:"Global Mobility / Expatriate Tax",u:"https://tahmidurrahman.com/placeholder/intl/global-mobility"}],
"tax-controversy": [{t:"Show-Cause & Notices Responses",u:"https://tahmidurrahman.com/placeholder/disputes/show-cause-replies"},{t:"Audit & Investigation Defense",u:"https://tahmidurrahman.com/placeholder/disputes/audit-investigation"},{t:"Tax ADR & Settlement",u:"https://tahmidurrahman.com/placeholder/disputes/adr"},{t:"Appeals before Commissioner (Appeals)",u:"https://tahmidurrahman.com/placeholder/disputes/commissioner-appeals"},{t:"Tax Appellate Tribunal Litigation",u:"https://tahmidurrahman.com/placeholder/disputes/tribunal"},{t:"High Court Writs on Tax",u:"https://tahmidurrahman.com/placeholder/disputes/high-court-writs"},{t:"Advance Ruling Appeals",u:"https://tahmidurrahman.com/placeholder/disputes/advance-ruling-appeals"},{t:"Mutual Agreement Procedure (MAP)",u:"https://tahmidurrahman.com/placeholder/disputes/map"},{t:"Penalty & Interest Mitigation",u:"https://tahmidurrahman.com/placeholder/disputes/penalty-interest"},{t:"Refund Claims & Follow-up",u:"https://tahmidurrahman.com/placeholder/disputes/refund-claims"},{t:"Search & Seizure Response",u:"https://tahmidurrahman.com/placeholder/disputes/search-seizure"},{t:"Stay of Demand / Guarantees",u:"https://tahmidurrahman.com/placeholder/disputes/stay-of-demand"},{t:"Compounding & Settlement",u:"https://tahmidurrahman.com/placeholder/disputes/compounding"},{t:"Prosecution Defense (Tax Offences)",u:"https://tahmidurrahman.com/placeholder/disputes/prosecution-defense"},{t:"Rectification & Amendments",u:"https://tahmidurrahman.com/placeholder/disputes/rectification"},{t:"Strategic Settlement & Mediation",u:"https://tahmidurrahman.com/placeholder/disputes/strategic-settlement"}],
"hc-writs": [{t:"Writ of Mandamus",u:"https://tahmidurrahman.com/placeholder/high-court/writs/mandamus"},{t:"Writ of Certiorari",u:"https://tahmidurrahman.com/placeholder/high-court/writs/certiorari"},{t:"Writ of Prohibition",u:"https://tahmidurrahman.com/placeholder/high-court/writs/prohibition"},{t:"Habeas Corpus",u:"https://tahmidurrahman.com/placeholder/high-court/writs/habeas-corpus"},{t:"Quo Warranto",u:"https://tahmidurrahman.com/placeholder/high-court/writs/quo-warranto"},{t:"Public Interest Litigation (PIL)",u:"https://tahmidurrahman.com/placeholder/high-court/writs/pil"},{t:"Interim Relief & Stay Orders",u:"https://tahmidurrahman.com/placeholder/high-court/writs/interim-stay"},{t:"Contempt Proceedings",u:"https://tahmidurrahman.com/placeholder/high-court/writs/contempt"},{t:"Service Matters & Promotions",u:"https://tahmidurrahman.com/placeholder/high-court/writs/service-matters"},{t:"Tender & Procurement Challenges",u:"https://tahmidurrahman.com/placeholder/high-court/writs/tender-procurement"},{t:"Environmental & Regulatory Writs",u:"https://tahmidurrahman.com/placeholder/high-court/writs/environment"},{t:"Election & Local Govt Writs",u:"https://tahmidurrahman.com/placeholder/high-court/writs/election"},{t:"Fundamental Rights Enforcement",u:"https://tahmidurrahman.com/placeholder/high-court/writs/fundamental-rights"},{t:"Judicial Review of Policy",u:"https://tahmidurrahman.com/placeholder/high-court/writs/policy-review"},{t:"Rule Nisi & Final Hearing",u:"https://tahmidurrahman.com/placeholder/high-court/writs/rule-nisi"},{t:"Enforcement of Writ Judgments",u:"https://tahmidurrahman.com/placeholder/high-court/writs/execution-enforcement"}],
"hc-civil": [{t:"First Appeals",u:"https://tahmidurrahman.com/placeholder/high-court/civil/first-appeals"},{t:"Second Appeals",u:"https://tahmidurrahman.com/placeholder/high-court/civil/second-appeals"},{t:"Revisions under CPC",u:"https://tahmidurrahman.com/placeholder/high-court/civil/revision-cpc"},{t:"Injunctions & Interim Applications",u:"https://tahmidurrahman.com/placeholder/high-court/civil/injunctions"},{t:"Execution Proceedings",u:"https://tahmidurrahman.com/placeholder/high-court/civil/execution"},{t:"Decree & Judgment Challenges",u:"https://tahmidurrahman.com/placeholder/high-court/civil/decree-challenges"},{t:"Arbitration-Related Appeals",u:"https://tahmidurrahman.com/placeholder/high-court/civil/arbitration-appeals"},{t:"Commercial Court Appeals",u:"https://tahmidurrahman.com/placeholder/high-court/civil/commercial-court"},{t:"Condonation of Delay & Limitation",u:"https://tahmidurrahman.com/placeholder/high-court/civil/limitation"},{t:"Restoration & Recall Applications",u:"https://tahmidurrahman.com/placeholder/high-court/civil/restoration"},{t:"Order IX / Ex-parte Matters",u:"https://tahmidurrahman.com/placeholder/high-court/civil/order-ix"},{t:"Summary Judgment & O.XIII-A",u:"https://tahmidurrahman.com/placeholder/high-court/civil/summary-judgment"},{t:"Declaratory & Specific Relief",u:"https://tahmidurrahman.com/placeholder/high-court/civil/declaratory-relief"},{t:"Partition & Property Disputes",u:"https://tahmidurrahman.com/placeholder/high-court/civil/partition-property"},{t:"Land & Revenue Appeals",u:"https://tahmidurrahman.com/placeholder/high-court/civil/land-revenue"},{t:"Case Strategy & Briefing",u:"https://tahmidurrahman.com/placeholder/high-court/civil/case-strategy"}],
"hc-criminal": [{t:"Bail & Anticipatory Bail Appeals",u:"https://tahmidurrahman.com/placeholder/high-court/criminal/bail-appeals"},{t:"Quashment under s. 561A",u:"https://tahmidurrahman.com/placeholder/high-court/criminal/quashment"},{t:"Conviction & Acquittal Appeals",u:"https://tahmidurrahman.com/placeholder/high-court/criminal/conviction-appeals"},{t:"Revisions under CrPC",u:"https://tahmidurrahman.com/placeholder/high-court/criminal/revision-crpc"},{t:"Suspension of Sentence",u:"https://tahmidurrahman.com/placeholder/high-court/criminal/sentence-suspension"},{t:"Death Reference Matters",u:"https://tahmidurrahman.com/placeholder/high-court/criminal/death-reference"},{t:"Remand & Custody Challenges",u:"https://tahmidurrahman.com/placeholder/high-court/criminal/remand-custody"},{t:"Cybercrime & ICT Act Appeals",u:"https://tahmidurrahman.com/placeholder/high-court/criminal/cybercrime"},{t:"Narcotics Control Appeals",u:"https://tahmidurrahman.com/placeholder/high-court/criminal/narcotics"},{t:"Anti-Corruption Commission Cases",u:"https://tahmidurrahman.com/placeholder/high-court/criminal/acc"},{t:"Special Tribunal Appeals",u:"https://tahmidurrahman.com/placeholder/high-court/criminal/tribunal-appeals"},{t:"Witness Protection Orders",u:"https://tahmidurrahman.com/placeholder/high-court/criminal/witness-protection"},{t:"Compounding of Offences",u:"https://tahmidurrahman.com/placeholder/high-court/criminal/compoundable"},{t:"FIR & Proceedings Quash",u:"https://tahmidurrahman.com/placeholder/high-court/criminal/fir-quash"},{t:"Transfer of Cases",u:"https://tahmidurrahman.com/placeholder/high-court/criminal/transfer"},{t:"Interim Relief & Directions",u:"https://tahmidurrahman.com/placeholder/high-court/criminal/interim-relief"}],
"hc-special": [{t:"Company Winding Up & Insolvency",u:"https://tahmidurrahman.com/placeholder/high-court/special/company-winding-up"},{t:"Scheme of Amalgamation/Arrangement",u:"https://tahmidurrahman.com/placeholder/high-court/special/company-amalgamation"},{t:"Oppression & Mismanagement",u:"https://tahmidurrahman.com/placeholder/high-court/special/company-oppression"},{t:"Shareholder Disputes",u:"https://tahmidurrahman.com/placeholder/high-court/special/company-shareholder"},{t:"Admiralty: Arrest & Release of Vessels",u:"https://tahmidurrahman.com/placeholder/high-court/special/admiralty-arrest"},{t:"Maritime Collision & Salvage",u:"https://tahmidurrahman.com/placeholder/high-court/special/admiralty-collision"},{t:"Banking Companies Matters",u:"https://tahmidurrahman.com/placeholder/high-court/special/banking-company"},{t:"Insurance & Reinsurance References",u:"https://tahmidurrahman.com/placeholder/high-court/special/insurance"},{t:"Securities Law & BSEC References",u:"https://tahmidurrahman.com/placeholder/high-court/special/securities"},{t:"IP Appeals (Trademark/Patent)",u:"https://tahmidurrahman.com/placeholder/high-court/special/ip-appeals"},{t:"Income Tax / VAT References",u:"https://tahmidurrahman.com/placeholder/high-court/special/tax-reference"},{t:"Competition Commission Challenges",u:"https://tahmidurrahman.com/placeholder/high-court/special/competition"},{t:"Education & Health Regulatory Matters",u:"https://tahmidurrahman.com/placeholder/high-court/special/education-health"},{t:"Arbitration Award Enforcement",u:"https://tahmidurrahman.com/placeholder/high-court/special/arbitration-enforcement"},{t:"Company/Admiralty Contempt",u:"https://tahmidurrahman.com/placeholder/high-court/special/contempt"},{t:"Letters Patent/Division Bench Appeals",u:"https://tahmidurrahman.com/placeholder/high-court/special/letters-patent-appeal"}],};

(function renderTRWPracticeGroups(){
const right=document.getElementById("trw-practices-right");
const order=[
"corporate-law","commercial-law","international-business","regulatory-compliance","banking-finance","investment-law","equity","fintech-crypto","business-immigration","family-immigration","investor-visas","citizenship-naturalization","real-estate","property-development","construction-law","land-acquisition","family-divorce","family-custody","family-matrimonial","family-international","adr-arbitration","adr-mediation","adr-conciliation","adr-other","criminal-domestic","criminal-international","criminal-corporate","criminal-compliance","ip-domestic","ip-international","ip-enforcement","ip-licensing","corporate-tax","indirect-tax","international-tax","tax-controversy","hc-writs","hc-civil","hc-criminal","hc-special"];
order.forEach((key,idx)=>{
const heading=TRW_HEADINGS[key]||"Services";
const items=(TRW_SERVICES[key]||[]).slice(0,16);
while(items.length<16){items.push(P(`${key}/coming-soon-${items.length+1}`,"TBD — Placeholder"));}
const group=document.createElement("div");
group.className="subcategory-group"+(idx===0?" active":"");
group.setAttribute("data-subcategory-group",key);
const section=document.createElement("div");
section.className="submenu-section";
const h4=document.createElement("h4"); h4.textContent=heading;
const ul=document.createElement("ul"); ul.className="submenu-list";
items.forEach(({t,u})=>{
const li=document.createElement("li"); li.className="submenu-item";
const a=document.createElement("a"); a.className="submenu-link"; a.href=u; a.textContent=t;
li.appendChild(a); ul.appendChild(li);
});
section.appendChild(h4); section.appendChild(ul); group.appendChild(section); right.appendChild(group);
});
})();
